<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('bangunan_kriterias', function (Blueprint $table) {
            $table->id();
            $table->string('jenis_kategori')->nullable();

            $table->foreignId('bangunan_id')->nullable()->constrained('bangunans')->cascadeOnDelete();
            $table->integer('markahTL')->nullable();
            $table->integer('markahKT')->nullable();
            $table->integer('markahSB')->nullable();
            $table->integer('markahPD')->nullable();
            $table->integer('markahFL')->nullable();
            $table->integer('markahIN')->nullable();    
            $table->integer('markahPA')->nullable();  
            
            $table->integer('markahTL32_MMR')->nullable();
            $table->integer('markahTL32_MS')->nullable();
            $table->integer('markahTL32_MR')->nullable();
            $table->integer('markahTL32_MMV')->nullable();
            $table->integer('markahTL32_MSV')->nullable();
            $table->integer('markahTL32_ML')->nullable();   
            
            $table->integer('markahPA32_MMR')->nullable();
            $table->integer('markahPA32_MS')->nullable();
            $table->integer('markahPA32_MR')->nullable();
            $table->integer('markahPA32_MMV')->nullable();
            $table->integer('markahPA32_MSV')->nullable();
            $table->integer('markahPA32_ML')->nullable();  
            




            $table->integer('markahTOTAL_TL_MMR')->nullable();
            $table->integer('markahTOTAL_TL_MS')->nullable();
            $table->integer('markahTOTAL_TL_MR')->nullable();
            $table->integer('markahTOTAL_TL_MMV')->nullable();
            $table->integer('markahTOTAL_TL_MSV')->nullable();
            $table->integer('markahTOTAL_TL_ML')->nullable();

            $table->integer('markahTOTAL_KT_MMR')->nullable();
            $table->integer('markahTOTAL_KT_MS')->nullable();
            $table->integer('markahTOTAL_KT_MR')->nullable();
            $table->integer('markahTOTAL_KT_MMV')->nullable();
            $table->integer('markahTOTAL_KT_MSV')->nullable();
            $table->integer('markahTOTAL_KT_ML')->nullable();

            $table->integer('markahTOTAL_SB_MMR')->nullable();
            $table->integer('markahTOTAL_SB_MS')->nullable();
            $table->integer('markahTOTAL_SB_MR')->nullable();
            $table->integer('markahTOTAL_SB_MMV')->nullable();
            $table->integer('markahTOTAL_SB_MSV')->nullable();
            $table->integer('markahTOTAL_SB_ML')->nullable();

            $table->integer('markahTOTAL_PA_MMR')->nullable();
            $table->integer('markahTOTAL_PA_MS')->nullable();
            $table->integer('markahTOTAL_PA_MR')->nullable();
            $table->integer('markahTOTAL_PA_MMV')->nullable();
            $table->integer('markahTOTAL_PA_MSV')->nullable();
            $table->integer('markahTOTAL_PA_ML')->nullable();

            $table->integer('markahTOTAL_PD_MMR')->nullable();
            $table->integer('markahTOTAL_PD_MS')->nullable();
            $table->integer('markahTOTAL_PD_MR')->nullable();
            $table->integer('markahTOTAL_PD_MMV')->nullable();
            $table->integer('markahTOTAL_PD_MSV')->nullable();
            $table->integer('markahTOTAL_PD_ML')->nullable();

            $table->integer('markahTOTAL_FL_MMR')->nullable();
            $table->integer('markahTOTAL_FL_MS')->nullable();
            $table->integer('markahTOTAL_FL_MR')->nullable();
            $table->integer('markahTOTAL_FL_MMV')->nullable();
            $table->integer('markahTOTAL_FL_MSV')->nullable();
            $table->integer('markahTOTAL_FL_ML')->nullable();

            $table->integer('markahTOTAL_IN_MMR')->nullable();
            $table->integer('markahTOTAL_IN_MS')->nullable();
            $table->integer('markahTOTAL_IN_MR')->nullable();
            $table->integer('markahTOTAL_IN_MMV')->nullable();
            $table->integer('markahTOTAL_IN_MSV')->nullable();
            $table->integer('markahTOTAL_IN_ML')->nullable();

            $table->integer('markahMMR')->nullable();
            $table->integer('markahMS')->nullable();
            $table->integer('markahMR')->nullable();
            $table->integer('markahMMV')->nullable();
            $table->integer('markahMSV')->nullable();
            $table->integer('markahML')->nullable();

            $table->integer('markahTL1_MR_PUN')->nullable();
            $table->integer('markahTL2_MR_PUN')->nullable();
            $table->integer('markahTL3_MR_PUN')->nullable();
            $table->integer('markahTL32_MR_PUN')->nullable();
            $table->integer('markahTL4_MR_PUN')->nullable();
            $table->integer('markahTL5_MR_PUN')->nullable();
            $table->integer('markahTL6_MR_PUN')->nullable();
            $table->integer('markahTL7_MR_PUN')->nullable();
            $table->integer('markahTL8_MR_PUN')->nullable();
            $table->integer('markahTL81_MR_PUN')->nullable();
            $table->integer('markahTL82_MR_PUN')->nullable();
            $table->integer('markahTL83_MR_PUN')->nullable();
            $table->integer('markahTL84_MR_PUN')->nullable();
            $table->integer('markahTL85_MR_PUN')->nullable();
            $table->integer('markahTL9_MR_PUN')->nullable();
            $table->integer('markahTL91_MR_PUN')->nullable();
            $table->integer('markahTL92_MR_PUN')->nullable();
            $table->integer('markahTL10_MR_PUN')->nullable();

            $table->integer('markahKT1_MR_PUN')->nullable();
            $table->integer('markahKT2_MR_PUN')->nullable();
            $table->integer('markahKT21_MR_PUN')->nullable();
            $table->integer('markahKT22_MR_PUN')->nullable();
            $table->integer('markahKT3_MR_PUN')->nullable();
            $table->integer('markahKT31_MR_PUN')->nullable();
            $table->integer('markahKT32_MR_PUN')->nullable();
            $table->integer('markahKT4_MR_PUN')->nullable();
            $table->integer('markahKT5_MR_PUN')->nullable();
            $table->integer('markahKT51_MR_PUN')->nullable();
            $table->integer('markahKT52_MR_PUN')->nullable();
            $table->integer('markahKT53_MR_PUN')->nullable();
            $table->integer('markahKT6_MR_PUN')->nullable();
            $table->integer('markahKT61_MR_PUN')->nullable();
            $table->integer('markahKT62_MR_PUN')->nullable();
            $table->integer('markahKT7_MR_PUN')->nullable();
            $table->integer('markahKT8_MR_PUN')->nullable();
            $table->integer('markahKT9_MR_PUN')->nullable();
            $table->integer('markahKT10_MR_PUN')->nullable();
            $table->integer('markahKT101_MR_PUN')->nullable();
            $table->integer('markahKT102_MR_PUN')->nullable();
            $table->integer('markahKT103_MR_PUN')->nullable();
            $table->integer('markahKT11_MR_PUN')->nullable();

            $table->integer('markahSB1_MR_PUN')->nullable();
            $table->integer('markahSB2_MR_PUN')->nullable();
            $table->integer('markahSB3_MR_PUN')->nullable();
            $table->integer('markahSB4_MR_PUN')->nullable();

            $table->integer('markahPA1_MR_PUN')->nullable();
            $table->integer('markahPA2_MR_PUN')->nullable();
            $table->integer('markahPA3_MR_PUN')->nullable();
            $table->integer('markahPA32_MR_PUN')->nullable();
            $table->integer('markahPA4_MR_PUN')->nullable();
            $table->integer('markahPA5_MR_PUN')->nullable();

            $table->integer('markahPD1_MR_PUN')->nullable();
            $table->integer('markahPD2_MR_PUN')->nullable();
            $table->integer('markahPD21_MR_PUN')->nullable();
            $table->integer('markahPD22_MR_PUN')->nullable();
            $table->integer('markahPD23_MR_PUN')->nullable();
            $table->integer('markahPD24_MR_PUN')->nullable();
            $table->integer('markahPD25_MR_PUN')->nullable();
            $table->integer('markahPD3_MR_PUN')->nullable();
            $table->integer('markahPD31_MR_PUN')->nullable();
            $table->integer('markahPD32_MR_PUN')->nullable();
            $table->integer('markahPD33_MR_PUN')->nullable();
            $table->integer('markahPD34_MR_PUN')->nullable();
            $table->integer('markahPD35_MR_PUN')->nullable();
            $table->integer('markahPD4_MR_PUN')->nullable();
            $table->integer('markahPD41_MR_PUN')->nullable();
            $table->integer('markahPD42_MR_PUN')->nullable();
            $table->integer('markahPD5_MR_PUN')->nullable();
            $table->integer('markahPD51_MR_PUN')->nullable();
            $table->integer('markahPD52_MR_PUN')->nullable();
            $table->integer('markahPD6_MR_PUN')->nullable();
            $table->integer('markahPD61_MR_PUN')->nullable();
            $table->integer('markahPD62_MR_PUN')->nullable();
            $table->integer('markahPD7_MR_PUN')->nullable();
            $table->integer('markahPD8_MR_PUN')->nullable();
            $table->integer('markahPD9_MR_PUN')->nullable();
            $table->integer('markahPD10_MR_PUN')->nullable();

            $table->integer('markahFL1_MR_PUN')->nullable();
            $table->integer('markahFL2_MR_PUN')->nullable();
            $table->integer('markahFL21_MR_PUN')->nullable();
            $table->integer('markahFL22_MR_PUN')->nullable();
            $table->integer('markahFL23_MR_PUN')->nullable();
            $table->integer('markahFL3_MR_PUN')->nullable();
            $table->integer('markahFL31_MR_PUN')->nullable();
            $table->integer('markahFL32_MR_PUN')->nullable();
            $table->integer('markahFL33_MR_PUN')->nullable();
            $table->integer('markahFL34_MR_PUN')->nullable();
        
            $table->integer('markahIN1_MR_PUN')->nullable();


            $table->integer('markahTL1_MV_PUN')->nullable();
            $table->integer('markahTL2_MV_PUN')->nullable();
            $table->integer('markahTL3_MV_PUN')->nullable();
            $table->integer('markahTL32_MV_PUN')->nullable();
            $table->integer('markahTL4_MV_PUN')->nullable();
            $table->integer('markahTL5_MV_PUN')->nullable();
            $table->integer('markahTL6_MV_PUN')->nullable();
            $table->integer('markahTL7_MV_PUN')->nullable();
            $table->integer('markahTL8_MV_PUN')->nullable();
            $table->integer('markahTL81_MV_PUN')->nullable();
            $table->integer('markahTL82_MV_PUN')->nullable();
            $table->integer('markahTL83_MV_PUN')->nullable();
            $table->integer('markahTL84_MV_PUN')->nullable();
            $table->integer('markahTL85_MV_PUN')->nullable();
            $table->integer('markahTL9_MV_PUN')->nullable();
            $table->integer('markahTL91_MV_PUN')->nullable();
            $table->integer('markahTL92_MV_PUN')->nullable();
            $table->integer('markahTL10_MV_PUN')->nullable();

            $table->integer('markahKT1_MV_PUN')->nullable();
            $table->integer('markahKT2_MV_PUN')->nullable();
            $table->integer('markahKT21_MV_PUN')->nullable();
            $table->integer('markahKT22_MV_PUN')->nullable();
            $table->integer('markahKT3_MV_PUN')->nullable();
            $table->integer('markahKT31_MV_PUN')->nullable();
            $table->integer('markahKT32_MV_PUN')->nullable();
            $table->integer('markahKT4_MV_PUN')->nullable();
            $table->integer('markahKT5_MV_PUN')->nullable();
            $table->integer('markahKT51_MV_PUN')->nullable();
            $table->integer('markahKT52_MV_PUN')->nullable();
            $table->integer('markahKT53_MV_PUN')->nullable();
            $table->integer('markahKT6_MV_PUN')->nullable();
            $table->integer('markahKT61_MV_PUN')->nullable();
            $table->integer('markahKT62_MV_PUN')->nullable();
            $table->integer('markahKT7_MV_PUN')->nullable();
            $table->integer('markahKT8_MV_PUN')->nullable();
            $table->integer('markahKT9_MV_PUN')->nullable();
            $table->integer('markahKT10_MV_PUN')->nullable();
            $table->integer('markahKT101_MV_PUN')->nullable();
            $table->integer('markahKT102_MV_PUN')->nullable();
            $table->integer('markahKT103_MV_PUN')->nullable();
            $table->integer('markahKT11_MV_PUN')->nullable();

            $table->integer('markahSB1_MV_PUN')->nullable();
            $table->integer('markahSB2_MV_PUN')->nullable();
            $table->integer('markahSB3_MV_PUN')->nullable();
            $table->integer('markahSB4_MV_PUN')->nullable();

            $table->integer('markahPA1_MV_PUN')->nullable();
            $table->integer('markahPA2_MV_PUN')->nullable();
            $table->integer('markahPA3_MV_PUN')->nullable();
            $table->integer('markahPA32_MV_PUN')->nullable();
            $table->integer('markahPA4_MV_PUN')->nullable();
            $table->integer('markahPA5_MV_PUN')->nullable();

            $table->integer('markahPD1_MV_PUN')->nullable();
            $table->integer('markahPD2_MV_PUN')->nullable();
            $table->integer('markahPD21_MV_PUN')->nullable();
            $table->integer('markahPD22_MV_PUN')->nullable();
            $table->integer('markahPD23_MV_PUN')->nullable();
            $table->integer('markahPD24_MV_PUN')->nullable();
            $table->integer('markahPD25_MV_PUN')->nullable();
            $table->integer('markahPD3_MV_PUN')->nullable();
            $table->integer('markahPD31_MV_PUN')->nullable();
            $table->integer('markahPD32_MV_PUN')->nullable();
            $table->integer('markahPD33_MV_PUN')->nullable();
            $table->integer('markahPD34_MV_PUN')->nullable();
            $table->integer('markahPD35_MV_PUN')->nullable();
            $table->integer('markahPD4_MV_PUN')->nullable();
            $table->integer('markahPD41_MV_PUN')->nullable();
            $table->integer('markahPD42_MV_PUN')->nullable();
            $table->integer('markahPD5_MV_PUN')->nullable();
            $table->integer('markahPD51_MV_PUN')->nullable();
            $table->integer('markahPD52_MV_PUN')->nullable();
            $table->integer('markahPD6_MV_PUN')->nullable();
            $table->integer('markahPD61_MV_PUN')->nullable();
            $table->integer('markahPD62_MV_PUN')->nullable();
            $table->integer('markahPD7_MV_PUN')->nullable();
            $table->integer('markahPD8_MV_PUN')->nullable();
            $table->integer('markahPD9_MV_PUN')->nullable();
            $table->integer('markahPD10_MV_PUN')->nullable();

            $table->integer('markahFL1_MV_PUN')->nullable();
            $table->integer('markahFL2_MV_PUN')->nullable();
            $table->integer('markahFL21_MV_PUN')->nullable();
            $table->integer('markahFL22_MV_PUN')->nullable();
            $table->integer('markahFL23_MV_PUN')->nullable();
            $table->integer('markahFL3_MV_PUN')->nullable();
            $table->integer('markahFL31_MV_PUN')->nullable();
            $table->integer('markahFL32_MV_PUN')->nullable();
            $table->integer('markahFL33_MV_PUN')->nullable();
            $table->integer('markahFL34_MV_PUN')->nullable();
        
            $table->integer('markahIN1_MV_PUN')->nullable();


            $table->integer('markahTL7_MMR')->nullable();
            $table->integer('markahTL7_MS')->nullable();
            $table->integer('markahTL7_MR')->nullable();
            $table->integer('markahTL7_MMV')->nullable();
            $table->integer('markahTL7_MSV')->nullable();
            $table->integer('markahTL7_ML')->nullable();
            $table->integer('markahTL10_MMR')->nullable();
            $table->integer('markahTL10_MS')->nullable();
            $table->integer('markahTL10_MR')->nullable();
            $table->integer('markahTL10_MMV')->nullable();
            $table->integer('markahTL10_MSV')->nullable();
            $table->integer('markahTL10_ML')->nullable();

            $table->integer('markahKT51_MMR')->nullable();
            $table->integer('markahKT51_MS')->nullable();
            $table->integer('markahKT51_MR')->nullable();
            $table->integer('markahKT51_MMV')->nullable();
            $table->integer('markahKT51_MSV')->nullable();
            $table->integer('markahKT51_ML')->nullable();
            $table->integer('markahKT53_MMR')->nullable();
            $table->integer('markahKT53_MS')->nullable();
            $table->integer('markahKT53_MR')->nullable();
            $table->integer('markahKT53_MMV')->nullable();
            $table->integer('markahKT53_MSV')->nullable();
            $table->integer('markahKT53_ML')->nullable();
            $table->integer('markahKT6_MMR')->nullable();
            $table->integer('markahKT6_MS')->nullable();
            $table->integer('markahKT6_MR')->nullable();
            $table->integer('markahKT6_MMV')->nullable();
            $table->integer('markahKT6_MSV')->nullable();
            $table->integer('markahKT6_ML')->nullable();
            $table->integer('markahKT61_MMR')->nullable();
            $table->integer('markahKT61_MS')->nullable();
            $table->integer('markahKT61_MR')->nullable();
            $table->integer('markahKT61_MMV')->nullable();
            $table->integer('markahKT61_MSV')->nullable();
            $table->integer('markahKT61_ML')->nullable();
            $table->integer('markahKT7_MMR')->nullable();
            $table->integer('markahKT7_MS')->nullable();
            $table->integer('markahKT7_MR')->nullable();
            $table->integer('markahKT7_MMV')->nullable();
            $table->integer('markahKT7_MSV')->nullable();
            $table->integer('markahKT7_ML')->nullable();
            $table->integer('markahKT9_MMR')->nullable();
            $table->integer('markahKT9_MS')->nullable();
            $table->integer('markahKT9_MR')->nullable();
            $table->integer('markahKT9_MMV')->nullable();
            $table->integer('markahKT9_MSV')->nullable();
            $table->integer('markahKT9_ML')->nullable();
            $table->integer('markahKT10_MMR')->nullable();
            $table->integer('markahKT10_MS')->nullable();
            $table->integer('markahKT10_MR')->nullable();
            $table->integer('markahKT10_MMV')->nullable();
            $table->integer('markahKT10_MSV')->nullable();
            $table->integer('markahKT10_ML')->nullable();
            $table->integer('markahKT101_MMR')->nullable();
            $table->integer('markahKT101_MS')->nullable();
            $table->integer('markahKT101_MR')->nullable();
            $table->integer('markahKT101_MMV')->nullable();
            $table->integer('markahKT101_MSV')->nullable();
            $table->integer('markahKT101_ML')->nullable();
            $table->integer('markahKT102_MMR')->nullable();
            $table->integer('markahKT102_MS')->nullable();
            $table->integer('markahKT102_MR')->nullable();
            $table->integer('markahKT102_MMV')->nullable();
            $table->integer('markahKT102_MSV')->nullable();
            $table->integer('markahKT102_ML')->nullable();
            $table->integer('markahKT103_MMR')->nullable();
            $table->integer('markahKT103_MS')->nullable();
            $table->integer('markahKT103_MR')->nullable();
            $table->integer('markahKT103_MMV')->nullable();
            $table->integer('markahKT103_MSV')->nullable();
            $table->integer('markahKT103_ML')->nullable();
            
            $table->integer('markahPA4_MMR')->nullable();
            $table->integer('markahPA4_MS')->nullable();
            $table->integer('markahPA4_MR')->nullable();
            $table->integer('markahPA4_MMV')->nullable();
            $table->integer('markahPA4_MSV')->nullable();
            $table->integer('markahPA4_ML')->nullable();
            $table->integer('markahPA5_MMR')->nullable();
            $table->integer('markahPA5_MS')->nullable();
            $table->integer('markahPA5_MR')->nullable();
            $table->integer('markahPA5_MMV')->nullable();
            $table->integer('markahPA5_MSV')->nullable();
            $table->integer('markahPA5_ML')->nullable();
            
            $table->integer('markahPD1_MMR')->nullable();
            $table->integer('markahPD1_MS')->nullable();
            $table->integer('markahPD1_MR')->nullable();
            $table->integer('markahPD1_MMV')->nullable();
            $table->integer('markahPD1_MSV')->nullable();
            $table->integer('markahPD1_ML')->nullable();
            $table->integer('markahPD21_MMR')->nullable();
            $table->integer('markahPD21_MS')->nullable();
            $table->integer('markahPD21_MR')->nullable();
            $table->integer('markahPD21_MMV')->nullable();
            $table->integer('markahPD21_MSV')->nullable();
            $table->integer('markahPD21_ML')->nullable();
            $table->integer('markahPD22_MMR')->nullable();
            $table->integer('markahPD22_MS')->nullable();
            $table->integer('markahPD22_MR')->nullable();
            $table->integer('markahPD22_MMV')->nullable();
            $table->integer('markahPD22_MSV')->nullable();
            $table->integer('markahPD22_ML')->nullable();
            $table->integer('markahPD23_MMR')->nullable();
            $table->integer('markahPD23_MS')->nullable();
            $table->integer('markahPD23_MR')->nullable();
            $table->integer('markahPD23_MMV')->nullable();
            $table->integer('markahPD23_MSV')->nullable();
            $table->integer('markahPD23_ML')->nullable();
            $table->integer('markahPD35_MMR')->nullable();
            $table->integer('markahPD35_MS')->nullable();
            $table->integer('markahPD35_MR')->nullable();
            $table->integer('markahPD35_MMV')->nullable();
            $table->integer('markahPD35_MSV')->nullable();
            $table->integer('markahPD35_ML')->nullable();
            $table->integer('markahPD4_MMR')->nullable();
            $table->integer('markahPD4_MS')->nullable();
            $table->integer('markahPD4_MR')->nullable();
            $table->integer('markahPD4_MMV')->nullable();
            $table->integer('markahPD4_MSV')->nullable();
            $table->integer('markahPD4_ML')->nullable();
            $table->integer('markahPD42_MMR')->nullable();
            $table->integer('markahPD42_MS')->nullable();
            $table->integer('markahPD42_MR')->nullable();
            $table->integer('markahPD42_MMV')->nullable();
            $table->integer('markahPD42_MSV')->nullable();
            $table->integer('markahPD42_ML')->nullable();
            $table->integer('markahPD51_MMR')->nullable();
            $table->integer('markahPD51_MS')->nullable();
            $table->integer('markahPD51_MR')->nullable();
            $table->integer('markahPD51_MMV')->nullable();
            $table->integer('markahPD51_MSV')->nullable();
            $table->integer('markahPD51_ML')->nullable();
            $table->integer('markahPD52_MMR')->nullable();
            $table->integer('markahPD52_MS')->nullable();
            $table->integer('markahPD52_MR')->nullable();
            $table->integer('markahPD52_MMV')->nullable();
            $table->integer('markahPD52_MSV')->nullable();
            $table->integer('markahPD52_ML')->nullable();
            $table->integer('markahPD6_MMR')->nullable();
            $table->integer('markahPD6_MS')->nullable();
            $table->integer('markahPD6_MR')->nullable();
            $table->integer('markahPD6_MMV')->nullable();
            $table->integer('markahPD6_MSV')->nullable();
            $table->integer('markahPD6_ML')->nullable();
            $table->integer('markahPD61_MMR')->nullable();
            $table->integer('markahPD61_MS')->nullable();
            $table->integer('markahPD61_MR')->nullable();
            $table->integer('markahPD61_MMV')->nullable();
            $table->integer('markahPD61_MSV')->nullable();
            $table->integer('markahPD61_ML')->nullable();
            $table->integer('markahPD7_MMR')->nullable();
            $table->integer('markahPD7_MS')->nullable();
            $table->integer('markahPD7_MR')->nullable();
            $table->integer('markahPD7_MMV')->nullable();
            $table->integer('markahPD7_MSV')->nullable();
            $table->integer('markahPD7_ML')->nullable();
            $table->integer('markahPD9_MMR')->nullable();
            $table->integer('markahPD9_MS')->nullable();
            $table->integer('markahPD9_MR')->nullable();
            $table->integer('markahPD9_MMV')->nullable();
            $table->integer('markahPD9_MSV')->nullable();
            $table->integer('markahPD9_ML')->nullable();

            $table->integer('markahTL1_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL2_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL3_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL32_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL4_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL5_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL6_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL7_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL8_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL81_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL82_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL83_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL84_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL85_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL9_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL91_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL92_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahTL10_ULASAN_VERIFIKASI')->nullable();

            $table->integer('markahKT1_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT2_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT21_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT22_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT3_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT31_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT32_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT4_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT5_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT51_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT52_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT53_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT6_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT61_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT62_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT7_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT8_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT9_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT10_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT101_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT102_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT103_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahKT11_ULASAN_VERIFIKASI')->nullable();

            $table->integer('markahSB1_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahSB2_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahSB3_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahSB4_ULASAN_VERIFIKASI')->nullable();

            $table->integer('markahPA1_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPA2_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPA3_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPA32_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPA4_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPA5_ULASAN_VERIFIKASI')->nullable();

            $table->integer('markahPD1_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD2_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD21_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD22_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD23_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD24_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD25_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD3_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD31_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD32_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD33_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD34_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD35_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD4_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD41_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD42_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD5_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD51_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD52_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD6_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD61_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD62_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD7_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD8_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD9_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahPD10_ULASAN_VERIFIKASI')->nullable();

            $table->integer('markahFL1_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL2_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL21_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL22_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL23_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL3_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL31_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL32_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL33_ULASAN_VERIFIKASI')->nullable();
            $table->integer('markahFL34_ULASAN_VERIFIKASI')->nullable();
        
            $table->integer('markahIN1_ULASAN_VERIFIKASI')->nullable();
       
            $table->integer('markahTL1_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL2_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL3_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL32_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL4_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL5_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL6_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL7_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL8_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL81_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL82_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL83_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL84_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL85_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL9_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL91_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL92_ULASAN_VALIDASI')->nullable();
            $table->integer('markahTL10_ULASAN_VALIDASI')->nullable();

            $table->integer('markahKT1_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT2_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT21_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT22_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT3_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT31_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT32_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT4_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT5_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT51_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT52_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT53_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT6_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT61_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT62_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT7_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT8_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT9_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT10_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT101_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT102_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT103_ULASAN_VALIDASI')->nullable();
            $table->integer('markahKT11_ULASAN_VALIDASI')->nullable();

            $table->integer('markahSB1_ULASAN_VALIDASI')->nullable();
            $table->integer('markahSB2_ULASAN_VALIDASI')->nullable();
            $table->integer('markahSB3_ULASAN_VALIDASI')->nullable();
            $table->integer('markahSB4_ULASAN_VALIDASI')->nullable();

            $table->integer('markahPA1_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPA2_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPA3_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPA32_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPA4_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPA5_ULASAN_VALIDASI')->nullable();

            $table->integer('markahPD1_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD2_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD21_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD22_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD23_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD24_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD25_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD3_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD31_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD32_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD33_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD34_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD35_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD4_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD41_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD42_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD5_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD51_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD52_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD6_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD61_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD62_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD7_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD8_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD9_ULASAN_VALIDASI')->nullable();
            $table->integer('markahPD10_ULASAN_VALIDASI')->nullable();

            $table->integer('markahFL1_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL2_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL21_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL22_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL23_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL3_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL31_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL32_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL33_ULASAN_VALIDASI')->nullable();
            $table->integer('markahFL34_ULASAN_VALIDASI')->nullable();
        
            $table->integer('markahIN1_ULASAN_VALIDASI')->nullable();

            $table->integer('markahTL1_MMV_SEDIA')->nullable();
            $table->integer('markahTL2_MMV_SEDIA')->nullable();
            $table->integer('markahTL3_MMV_SEDIA')->nullable();
            $table->integer('markahTL32_MMV_SEDIA')->nullable();
            $table->integer('markahTL4_MMV_SEDIA')->nullable();
            $table->integer('markahTL5_MMV_SEDIA')->nullable();
            $table->integer('markahTL6_MMV_SEDIA')->nullable();
            $table->integer('markahTL7_MMV_SEDIA')->nullable();
            $table->integer('markahTL8_MMV_SEDIA')->nullable();
            $table->integer('markahTL81_MMV_SEDIA')->nullable();
            $table->integer('markahTL82_MMV_SEDIA')->nullable();
            $table->integer('markahTL83_MMV_SEDIA')->nullable();
            $table->integer('markahTL84_MMV_SEDIA')->nullable();
            $table->integer('markahTL85_MMV_SEDIA')->nullable();
            $table->integer('markahTL9_MMV_SEDIA')->nullable();
            $table->integer('markahTL91_MMV_SEDIA')->nullable();
            $table->integer('markahTL92_MMV_SEDIA')->nullable();
            $table->integer('markahTL10_MMV_SEDIA')->nullable();

            $table->integer('markahKT1_MMV_SEDIA')->nullable();
            $table->integer('markahKT2_MMV_SEDIA')->nullable();
            $table->integer('markahKT21_MMV_SEDIA')->nullable();
            $table->integer('markahKT22_MMV_SEDIA')->nullable();
            $table->integer('markahKT3_MMV_SEDIA')->nullable();
            $table->integer('markahKT31_MMV_SEDIA')->nullable();
            $table->integer('markahKT32_MMV_SEDIA')->nullable();
            $table->integer('markahKT4_MMV_SEDIA')->nullable();
            $table->integer('markahKT5_MMV_SEDIA')->nullable();
            $table->integer('markahKT51_MMV_SEDIA')->nullable();
            $table->integer('markahKT52_MMV_SEDIA')->nullable();
            $table->integer('markahKT53_MMV_SEDIA')->nullable();
            $table->integer('markahKT6_MMV_SEDIA')->nullable();
            $table->integer('markahKT61_MMV_SEDIA')->nullable();
            $table->integer('markahKT62_MMV_SEDIA')->nullable();
            $table->integer('markahKT7_MMV_SEDIA')->nullable();
            $table->integer('markahKT8_MMV_SEDIA')->nullable();
            $table->integer('markahKT9_MMV_SEDIA')->nullable();
            $table->integer('markahKT10_MMV_SEDIA')->nullable();
            $table->integer('markahKT101_MMV_SEDIA')->nullable();
            $table->integer('markahKT102_MMV_SEDIA')->nullable();
            $table->integer('markahKT103_MMV_SEDIA')->nullable();
            $table->integer('markahKT11_MMV_SEDIA')->nullable();

            $table->integer('markahSB1_MMV_SEDIA')->nullable();
            $table->integer('markahSB2_MMV_SEDIA')->nullable();
            $table->integer('markahSB3_MMV_SEDIA')->nullable();
            $table->integer('markahSB4_MMV_SEDIA')->nullable();

            $table->integer('markahPA1_MMV_SEDIA')->nullable();
            $table->integer('markahPA2_MMV_SEDIA')->nullable();
            $table->integer('markahPA3_MMV_SEDIA')->nullable();
            $table->integer('markahPA32_MMV_SEDIA')->nullable();
            $table->integer('markahPA4_MMV_SEDIA')->nullable();
            $table->integer('markahPA5_MMV_SEDIA')->nullable();

            $table->integer('markahPD1_MMV_SEDIA')->nullable();
            $table->integer('markahPD2_MMV_SEDIA')->nullable();
            $table->integer('markahPD21_MMV_SEDIA')->nullable();
            $table->integer('markahPD22_MMV_SEDIA')->nullable();
            $table->integer('markahPD23_MMV_SEDIA')->nullable();
            $table->integer('markahPD24_MMV_SEDIA')->nullable();
            $table->integer('markahPD25_MMV_SEDIA')->nullable();
            $table->integer('markahPD3_MMV_SEDIA')->nullable();
            $table->integer('markahPD31_MMV_SEDIA')->nullable();
            $table->integer('markahPD32_MMV_SEDIA')->nullable();
            $table->integer('markahPD33_MMV_SEDIA')->nullable();
            $table->integer('markahPD34_MMV_SEDIA')->nullable();
            $table->integer('markahPD35_MMV_SEDIA')->nullable();
            $table->integer('markahPD4_MMV_SEDIA')->nullable();
            $table->integer('markahPD41_MMV_SEDIA')->nullable();
            $table->integer('markahPD42_MMV_SEDIA')->nullable();
            $table->integer('markahPD5_MMV_SEDIA')->nullable();
            $table->integer('markahPD51_MMV_SEDIA')->nullable();
            $table->integer('markahPD52_MMV_SEDIA')->nullable();
            $table->integer('markahPD6_MMV_SEDIA')->nullable();
            $table->integer('markahPD61_MMV_SEDIA')->nullable();
            $table->integer('markahPD62_MMV_SEDIA')->nullable();
            $table->integer('markahPD7_MMV_SEDIA')->nullable();
            $table->integer('markahPD8_MMV_SEDIA')->nullable();
            $table->integer('markahPD9_MMV_SEDIA')->nullable();
            $table->integer('markahPD10_MMV_SEDIA')->nullable();

            $table->integer('markahFL1_MMV_SEDIA')->nullable();
            $table->integer('markahFL2_MMV_SEDIA')->nullable();
            $table->integer('markahFL21_MMV_SEDIA')->nullable();
            $table->integer('markahFL22_MMV_SEDIA')->nullable();
            $table->integer('markahFL23_MMV_SEDIA')->nullable();
            $table->integer('markahFL3_MMV_SEDIA')->nullable();
            $table->integer('markahFL31_MMV_SEDIA')->nullable();
            $table->integer('markahFL32_MMV_SEDIA')->nullable();
            $table->integer('markahFL33_MMV_SEDIA')->nullable();
            $table->integer('markahFL34_MMV_SEDIA')->nullable();

            $table->integer('markahIN1_MMV_SEDIA')->nullable();

            $table->integer('markahTOTAL_TL_MMV_SEDIA')->nullable();
            $table->integer('markahTOTAL_KT_MMV_SEDIA')->nullable();
            $table->integer('markahTOTAL_SB_MMV_SEDIA')->nullable();
            $table->integer('markahTOTAL_PA_MMV_SEDIA')->nullable();
            $table->integer('markahTOTAL_PD_MMV_SEDIA')->nullable();
            $table->integer('markahTOTAL_FL_MMV_SEDIA')->nullable();
            $table->integer('markahTOTAL_IN_MMV_SEDIA')->nullable();
            

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('bangunan_kriterias');
    }
};
